import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}

// // src/app/layout.tsx
// import type { Metadata } from 'next'
// import { Inter, DM_Serif_Display } from 'next/font/google'
// import './globals.css'

// const inter = Inter({ subsets: ['latin'], variable: '--font-sans' })
// const dmSerif = DM_Serif_Display({
//   subsets: ['latin'],
//   variable: '--font-serif',
// })

// export const metadata: Metadata = {
//   title: 'Holidaze',
//   description: 'Modern accommodation booking site',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       {/* expose font variables to CSS */}
//       <body className={`${inter.variable} ${dmSerif.variable} antialiased`}>
//         {children}
//       </body>
//     </html>
//   )
// }
